Classification for Wine using ANN
========================================================
```{r}
require(nnet)
```

Read in Data
--------------------
```{r}
wdata = read.csv("winequality-white.csv", header=TRUE)

summary(wdata)
nrow(wdata)

#Edit by JFK
wdata$quality<-as.factor(wdata$quality)
#nnet automatically classifies when it encounters the target variable as factor variable.Here our target is numeric.
```

Prepare the training and test data
```{r}
set.seed(12345)
#Training set 75% and Test set 25%
windexes<-sample(1:nrow(wdata),size=0.75*nrow(wdata))
#trainsize = 0.75 * nrow(data)
#train_data = data[0:trainsize,]
train_wdata = wdata[windexes,]
test_wdata = wdata[-windexes,]
```

Train the neural net and then predict the results using the test data
```{r}
#train the neural net
nn = nnet(wdata$quality ~ ., data = train_wdata, size = 10 )

results = predict(nn, test_data[,-9],type="class")
#Added param type="class" to predict the class membership instead of probablities. Also removing V9(target col) from data for prediction.
#-- No NEED TO round the prediction data now.Round the results and combine it with the test_data to analyze
#result_data = cbind(test_data, results, round(results))
result_data=cbind(test_data,results)

#Generating confusion matrix
confmat = table(result_data$V9,result_data$results)
accuracy = (confmat[1] + confmat[4]) / sum(confmat)
sensitivity = confmat[1]/(confmat[1] + confmat[2])
specificity = confmat[4]/(confmat[3] + confmat[4])


confmat
sprintf("Accuracy is %f", accuracy) 
sprintf("Sensitivity is %f", sensitivity)
sprintf("Specificity is %f", specificity)
```


